[package]
name = "qckprism"
version = "0.2.0"
authors = ["zapp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9.1"
byteorder = "1.3.4"
clap = "3.2.15"
hex = "0.4.2"
